apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: whatsapp-clone
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: bG96aW5rYTEyMzQ=
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOmxvemlua2ExMjM0QG1vbmdvLXNlcnZpY2U6MjcwMTcvV2hhdHNhcHBDbG9uZQ==